apiVersion: v1
kind: ServiceAccount
metadata:
  name: cvmfs-csi-nodeplugin
  namespace: cvmfs

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cvmfs-csi-nodeplugin
aggregationRule:
  clusterRoleSelectors:
    - matchLabels:
        rbac.cvmfs.csi.cern.ch/aggregate-to-cvmfs-csi-nodeplugin: "true"
rules: []
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cvmfs-csi-nodeplugin-rules
  labels:
    rbac.cvmfs.csi.cern.ch/aggregate-to-cvmfs-csi-nodeplugin: "true"
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "update"]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["volumeattachments"]
    verbs: ["get", "list", "watch", "update"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cvmfs-csi-nodeplugin
subjects:
  - kind: ServiceAccount
    name: cvmfs-csi-nodeplugin
    namespace: cvmfs
roleRef:
  kind: ClusterRole
  name: cvmfs-csi-nodeplugin
  apiGroup: rbac.authorization.k8s.io

  
